package com.app.bongda.util;

public class ByUtils {
	public static final String BASESERVER = "http://210.245.94.14:84/Services/wsfootball.asmx";
	public static final String wsFootBall_BangXepHang = "<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">  <soap:Body>    <wsFootBall_BangXepHang xmlns=\"http://tempuri.org/\">      <iID_MaGiai>bangxephangId</iID_MaGiai>    </wsFootBall_BangXepHang>  </soap:Body></soap:Envelope>";
	public static final String wsFootBall_FocusMatch = "<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">  <soap:Body>    <wsFootBall_Tran_Quan_Tam xmlns=\"http://tempuri.org/\">    \t<sMaTran>%d</sMaTran>    </wsFootBall_Tran_Quan_Tam>  </soap:Body></soap:Envelope>";
	public static final String wsFootBall_Giai_Theo_QuocGia = "<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">  <soap:Body>    <wsFootBall_Giai_Theo_QuocGia xmlns=\"http://tempuri.org/\">      <iID_MaQuocGia>quocgiaid</iID_MaQuocGia>    </wsFootBall_Giai_Theo_QuocGia>  </soap:Body></soap:Envelope>";
	public static final String wsFootBall_Lives = "<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">  <soap:Body>    <wsFootBall_Lives xmlns=\"http://tempuri.org/\" />  </soap:Body></soap:Envelope>";
	public static final String wsFootBall_Lives_Theo_Giai = "<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">  <soap:Body>    <wsFootBall_Lives_Theo_Giai xmlns=\"http://tempuri.org/\">      <iID_MaGiai>magiai</iID_MaGiai>    </wsFootBall_Lives_Theo_Giai>  </soap:Body></soap:Envelope>";
	public static final String wsFootBall_MatchDetail = "<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">  <soap:Body>    <wsFootBall_ChiTiet_Tran xmlns=\"http://tempuri.org/\">    \t<iID_MaTran>%d</iID_MaTran>    </wsFootBall_ChiTiet_Tran>  </soap:Body></soap:Envelope>";
	public static final String wsFootBall_Nhan_Dinh_Chuyen_Gia = "<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">  <soap:Body>    <wsFootBall_Nhan_Dinh_Chuyen_Gia xmlns=\"http://tempuri.org/\">      <iID_MaGiai>iID_MaNhanDinh_Info</iID_MaGiai>    </wsFootBall_Nhan_Dinh_Chuyen_Gia>  </soap:Body></soap:Envelope>";
	public static final String wsFootBall_Nhan_Dinh_Chuyen_Gia_Theo_Tran = "<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">  <soap:Body>    <wsFootBall_Nhan_Dinh_Chuyen_Gia_Theo_Tran xmlns=\"http://tempuri.org/\">      <sMaTran>%d</sMaTran>    </wsFootBall_Nhan_Dinh_Chuyen_Gia_Theo_Tran>  </soap:Body></soap:Envelope>";
	public static final String wsFootBall_Phong_Do = "<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">  <soap:Body>    <wsFootBall_Phong_Do xmlns=\"http://tempuri.org/\">    \t<sMaTran>%d</sMaTran>    </wsFootBall_Phong_Do>  </soap:Body></soap:Envelope>";
	public static final String wsFootBall_Quocgia = "<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">  <soap:Body>    <wsFootBall_Quocgia xmlns=\"http://tempuri.org/\" />  </soap:Body></soap:Envelope>";
	public static final int REQUEST = 1000;

}
